# Generated by Django 2.0.2 on 2018-04-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadImage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimage',
            name='user',
            field=models.IntegerField(default=None),
        ),
    ]
