# Generated by Django 2.0.2 on 2018-04-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadImage', '0002_testimage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimage',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
