# Generated by Django 2.0.2 on 2018-04-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadImage', '0003_auto_20180405_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimage',
            name='user',
            field=models.IntegerField(),
        ),
    ]
