# Generated by Django 2.0.2 on 2018-05-06 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploadImage', '0005_auto_20180405_1815'),
        ('uploadModel', '0005_auto_20180413_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.IntegerField()),
                ('feature_image', models.ImageField(upload_to='synthesised_features')),
                ('image', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='uploadImage.TestImage')),
                ('model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='uploadModel.TestModel')),
            ],
        ),
    ]
