# Generated by Django 2.0.2 on 2018-03-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('architecture', models.FileField(upload_to='models')),
                ('weights', models.FileField(upload_to='models')),
                ('labels', models.FileField(upload_to='models')),
            ],
        ),
    ]
