# Generated by Django 2.0.2 on 2018-04-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
