# Generated by Django 2.0.2 on 2018-04-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadModel', '0003_auto_20180409_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='checkpoint',
            field=models.FileField(null=True, upload_to='models'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='index_file',
            field=models.FileField(null=True, upload_to='models'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='labels',
            field=models.FileField(null=True, upload_to='models'),
        ),
    ]
