# Generated by Django 2.0.2 on 2018-04-13 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadModel', '0004_auto_20180409_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='checkpoint',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='index_file',
        ),
    ]
