# Generated by Django 2.0.2 on 2018-02-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadImage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimage',
            name='image',
        ),
    ]
