# Generated by Django 2.0.2 on 2018-02-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadImage', '0002_remove_testimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimage',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
